FROM node:latest

RUN useradd -ms /bin/bash admin

WORKDIR /app

COPY --chmod=0755 package.json package-lock.json /app/

RUN npm install
RUN npm install xlsx
RUN npm install isomorphic-fetch

COPY --chmod=0755 . /app

RUN chown -R admin:admin /app
RUN chmod 755 /app
USER admin

CMD ["npm", "run", "dev"]

