# Start with a base R image
FROM rocker/r-ver:4.2.1

# Install required packages
RUN apt-get update -qq && apt-get install -y \
      libssl-dev \
      libcurl4-gnutls-dev
      
RUN useradd -ms /bin/bash admin

# Install packages from CRAN and GitHub
RUN R -e "install.packages('plumber')"
RUN R -e "install.packages('readr')"
RUN R -e "install.packages('jsonlite', repos='http://cran.rstudio.com/')"

# copy everything from the current directory into the container
COPY --chmod=0755 / /app 
WORKDIR /app

RUN chown -R admin:admin /app
RUN chmod 755 /app
USER admin

ENV PATH="$PATH:/app/normalization_pipeline"

# open port 80 to traffic
EXPOSE 80

# when the container starts, star the main.R script 
ENTRYPOINT ["Rscript", "main.R"]
