# start the image
FROM rocker/r-ver:3.5.0

RUN useradd -ms /bin/bash admin

# install the linux libraries needed fro plumber
RUN apt-get update -qq && apt-get install -y \
libssl-dev \
libcurl4-gnutls-dev

# install plumber
RUN R -e "install.packages('plumber')"

# copy everything from the current directory into the container
COPY --chmod=0755 / /app 
WORKDIR /app

RUN chown -R admin:admin /app
RUN chmod 755 /app
USER admin

ENV PATH="$PATH:/app/normalization_pipeline"

# open port 80 to traffic
EXPOSE 80

# when the container starts, star the main.R script
ENTRYPOINT ["Rscript", "main.R"]
